#!/bin/bash

BACKUP_DIR="$HOME/backup"

# Utilities
function datetime() {
    date -u +%Y-%m-%dT%H:%M:%SZ
}

function ls_functions()
{
  functions | grep -E "^\w* \(\) \{" | grep -v ^_ | cut -d ' ' -f 1
}

function wgets()
{
  local H='--header'
  wget $H='Accept-Language: en-us,en;q=0.5' $H='Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' $H='Connection: keep-alive' -U       'Mozilla/5.0 (Windows NT 5.1; rv:10.0.2) Gecko/20100101 Firefox/10.0.2' --referer=http://www.askapache.com/ "$@";
}

# SSH

function sshn() {
    [ -z $1 ] && { 
        echo "Please provide a session name, aborting."
        return
    }

    local session=$1
    local window=$1
    local command="ssh"

    for host in $(cat -); do
        if [ $rown ]; then
            tmux split-window -h "$command $host"
            tmux select-layout tiled > /dev/null 
        fi
        if [ -z $rown ]; then
            local rown="yes"
            tmux new-session -d -n $window -s $session "$command $host"
        fi
    done
    tmux select-pane -t 0
    tmux set-window-option synchronize-panes on > /dev/null
}

# Git

git-recursive () {
  find . -iname .git -type d -prune -print -execdir git "$@" \;
}

# Code

function cd_repo()
{
  cd `ls -d $HOME/GitHub/* $HOME/GitHub/jumo/* | grep -i $@`
}

function repos()
{
  ls -d $HOME/GitHub/* $HOME/GitHub/jumo/* | grep -i $@
}


function sanegrep()
{
  # todo: doesn't work on Mac
  _pattern=$1
  grep -iEr --exclude *.js --exclude *.css --exclude *spec* --exclude tags $1 .
}

function virb()
{
  case `uname` in
    Darwin)
      vim `find -E . -iregex ".*/$1\.rb"`
      ;;
    Linux)
      vim `find -regex ".*/$1\.rb$"`
      ;;
  esac
}

function vimo()
{
  case `uname` in
    Darwin)
      vim `find -E . -iname $1`
      ;;
    Linux)
      vim `find -iname $1`
      ;;
  esac
}
